version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    labels:
      - github-actions
      - dependencies
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    labels:
      - dependencies
    groups:
      pip:
        patterns:
          - '*'
